/* {
  "id": 1918254,
  "name": "AlexProgrammer's Strategy",
  "description": "asd",
  "status": 5,
  "account": "25253332",
  "server": "RoboForex-Pro-5",
  "is_connected": 1,
  "is_mt5": 0,
  "account_type": 0
} */
const DataTopPerforming = [
  {
    username: "Clarisse",
    strategy: "stragegy-clarisse",
    chartImg: "home/top-performing/graph1.svg",
    risk: 5,
    roi: 51.25,
    timeFrame: "6 Months",
    userImg: "clarisse.png",
    strategyId: 1918254,
  },
  {
    username: "Naomi",
    strategy: "strategy-naomi",
    chartImg: "home/top-performing/graph1.svg",
    risk: 5,
    roi: 51.25,
    timeFrame: "6 Months",
    userImg: "naomi.png",
    strategyId: 1918255,
  },
  {
    username: "Joshua",
    strategy: "strategy-joshua",
    chartImg: "home/top-performing/graph3.svg",
    risk: 5,
    roi: 51.25,
    timeFrame: "6 Months",
    userImg: "face-male.png",
    strategyId: 1918256,
  },
  {
    username: "Janis",
    strategy: "strategy-janis",
    chartImg: "home/top-performing/graph1.svg",
    risk: 5,
    roi: 51.25,
    timeFrame: "6 Months",
    userImg: "face-male2.png",
    strategyId: 1918257,
  },
  {
    username: "Elizabeth",
    strategy: "strategy-elizabeth",
    chartImg: "home/top-performing/graph1.svg",
    risk: 5,
    roi: 51.25,
    timeFrame: "6 Months",
    userImg: "clarisse.png",
    strategyId: 1918257,
  },
  {
    username: "Margareth",
    strategy: "strategy-margareth",
    chartImg: "home/top-performing/graph1.svg",
    risk: 5,
    roi: 51.25,
    timeFrame: "6 Months",
    userImg: "naomi.png",
    strategyId: 1918258,
  },
];

export default DataTopPerforming;
