export default [
  {
    id: "n1",
    title: "Last week’s news",
    preview: "Bitcoin jumps as funds rotate back into risk assets.",
    timeAgo: "1 day ago",
    isRead: false,
  },
  {
    id: "n2",
    title: "Market wrap",
    preview: "S&P edges higher; energy leads while tech lags.",
    timeAgo: "2 hours ago",
    isRead: false,
  },
  {
    id: "n3",
    title: "Price alert",
    preview: "ETH breaks above $3,100 for the first time this month.",
    timeAgo: "4 hours ago",
    isRead: false,
  },
  {
    id: "n4",
    title: "Portfolio note",
    preview: "You received a $25 dividend from MSFT.",
    timeAgo: "7 hours ago",
    isRead: true,
  },
  {
    id: "n5",
    title: "Strategy tip",
    preview: "Rebalance suggests trimming overweight in BTC to 20%.",
    timeAgo: "10 hours ago",
    isRead: true,
  },
  {
    id: "n6",
    title: "Earnings update",
    preview: "NVDA beats on revenue; guidance raised for next quarter.",
    timeAgo: "12 hours ago",
    isRead: true,
  },
  {
    id: "n7",
    title: "Research",
    preview: "Institutional flows show steady accumulation in large caps.",
    timeAgo: "18 hours ago",
    isRead: true,
  },
  {
    id: "n8",
    title: "New listing",
    preview: "SOL/USDT margin pair is now available.",
    timeAgo: "22 hours ago",
    isRead: true,
  },
  {
    id: "n9",
    title: "Security reminder",
    preview: "Enable 2FA to protect withdrawals and API access.",
    timeAgo: "1 day ago",
    isRead: true,
  },
  {
    id: "n10",
    title: "Last week’s news",
    preview: "Oil spikes on supply risks; airlines under pressure.",
    timeAgo: "1 day ago",
    isRead: true,
  },
  {
    id: "n11",
    title: "Watchlist move",
    preview: "AAPL crosses above 50-day MA with rising volume.",
    timeAgo: "2 days ago",
    isRead: true,
  },
  {
    id: "n12",
    title: "Funding rates",
    preview: "Perp funding turns positive across majors.",
    timeAgo: "2 days ago",
    isRead: true,
  },
  {
    id: "n13",
    title: "Macro brief",
    preview: "CPI inline; odds of rate cut increase for Q3.",
    timeAgo: "2 days ago",
    isRead: true,
  },
  {
    id: "n14",
    title: "Strategy backtest",
    preview: "Mean-reversion (4h) shows 61% win rate YTD.",
    timeAgo: "3 days ago",
    isRead: true,
  },
  {
    id: "n15",
    title: "Feature update",
    preview: "You can link multiple broker accounts in Settings.",
    timeAgo: "3 days ago",
    isRead: true,
  },
  {
    id: "n16",
    title: "Compliance",
    preview: "KYC verification approved for your account.",
    timeAgo: "4 days ago",
    isRead: true,
  },
  {
    id: "n17",
    title: "Market wrap",
    preview: "Metals rally; dollar softens after payrolls.",
    timeAgo: "5 days ago",
    isRead: true,
  },
  {
    id: "n18",
    title: "News digest",
    preview: "ETF inflows hit a 3-week high; miners outperform.",
    timeAgo: "6 days ago",
    isRead: true,
  },
  {
    id: "n19",
    title: "Alert",
    preview: "Stop loss triggered on TSLA at $228.40.",
    timeAgo: "6 days ago",
    isRead: true,
  },
  {
    id: "n20",
    title: "Last week’s news",
    preview: "Altcoins mixed; DeFi TVL climbs to quarterly peak.",
    timeAgo: "7 days ago",
    isRead: true,
  },
];
